# **Case Study 3: Intensive Care Beds Forecasting. Comparisons amongs LSTM, GRU, BiLSTM, Vanilla Transformers and then we include adjustments by LLMs**

# **All Installations**

In [95]:
%pip install transformers datasets peft accelerate evaluate torch --quiet
%pip install python-dotenv

Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)

# **All Imports**

In [96]:
import os
import re
import random
import timeit
import numpy as np
import pandas as pd
from dotenv import load_dotenv
import warnings
from pathlib import Path
import statsmodels.api as sm
from tqdm.notebook import tqdm
from sklearn.metrics import mean_absolute_percentage_error, r2_score, root_mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import plotly.express as px
import matplotlib.pyplot as plt

# Deep Learning Imports
from tensorflow.keras import Input, Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GRU, LSTM, Bidirectional, Conv1D, GlobalAveragePooling1D, Dropout, MultiHeadAttention
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adam

# LLMs Imports
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# **Globals**

In [97]:
neural_model = "LSTM"         # LSTM, GRU, BiLSTM

# Dataset
dataset_url = "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv"
selected_region = "Lazio"

# **All Code, Models and Pictures dowloads**

In [124]:
!cp -rp "./env" ./.env 2>/dev/null
load_dotenv()

True

# **Initializations**

In [99]:
warnings.filterwarnings('ignore')

# **Hyper-parameters**

In [100]:
epochs = 250
batch_size = 256
neural_cells = 600
num_attention_heads = 4

# **Data Download**

In [101]:
df = pd.read_csv(dataset_url)
df.head()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,...,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido,codice_nuts_1,codice_nuts_2
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df_selected = df[df["denominazione_regione"] == selected_region]
df_selected = df_selected.sort_values("data")
y = df_selected["terapia_intensiva"].values.astype(float)

In [103]:
df_selected['data'] = pd.to_datetime(df_selected['data']).dt.floor('D')
df_selected['year_month'] = df_selected['data'].dt.to_period('M')

df_selected = (
    df_selected
    .drop_duplicates(subset=['year_month'], keep='first')
    [['data', 'terapia_intensiva']]
    .rename(columns={'data': 'Date', 'terapia_intensiva': 'y'})
    .reset_index(drop=True)
)

In [104]:
df_selected

         Date    y
0  2020-02-24    1
1  2020-03-01    0
2  2020-04-01  177
3  2020-05-01  105
4  2020-06-01   56
5  2020-07-01   12
6  2020-08-01    9
7  2020-09-01    8
8  2020-10-01   49
9  2020-11-01  185
10 2020-12-01  352
11 2021-01-01  305
12 2021-02-01  288
13 2021-03-01  223
14 2021-04-01  362
15 2021-05-01  276
16 2021-06-01  145
17 2021-07-01   47
18 2021-08-01   46
19 2021-09-01   71
20 2021-10-01   54
21 2021-11-01   57
22 2021-12-01   96
23 2022-01-01  153
24 2022-02-01  198
25 2022-03-01  116
26 2022-04-01   77
27 2022-05-01   62
28 2022-06-01   31
29 2022-07-01   55
30 2022-08-01   68
31 2022-09-01   41
32 2022-10-01   27
33 2022-11-01   32
34 2022-12-01   30
35 2023-01-01   24
36 2023-02-01   20
37 2023-03-01   24
38 2023-04-01   15
39 2023-05-01   12
40 2023-06-01   12
41 2023-07-01    8
42 2023-08-01    3
43 2023-09-01    4
44 2023-10-01   11
45 2023-11-01   12
46 2023-12-01   18
47 2024-01-01   21
48 2024-02-01   12
49 2024-03-01    6
50 2024-04-01    6
51 2024-05-01    2
52 2024-06-01    4
53 2024-07-01    2
54 2024-08-01    7
55 2024-09-01    8
56 2024-10-01    4
57 2024-11-01    3
58 2024-12-01    2
59 2025-01-01    1

# **General Functions Definition**

In [105]:
def rmse(y, yhat):
    return root_mean_squared_error(y, yhat)
    #return np.sqrt(np.mean((y - yhat)**2))

def mae(y, yhat):
    return np.mean(np.abs(y - yhat))

def mape(y, yhat):
    # mean_absolute_percentage_error from sklearn returns a fraction, multiply by 100 for percentage
    return mean_absolute_percentage_error(y, yhat)

def r2score(y_true, y_pred):
    return r2_score(y_true, y_pred)

def metrics_compute(metric_name, model_name, model = None, scaler = None, X_dataset = None, dataset_y = None, X_train = None, train_y = None, X_test = None, test_y = None, y_hat = None, y_true = None):

  if metric_name.lower() == "rmse":
    metric = rmse
  elif metric_name.lower() == "mae":
    metric = mae
  elif metric_name.lower() == "mape":
    metric = mape
  else:
    metric = r2_score

  if X_dataset is not None:
    y_hat_data, y_true_data = denormalize_real_and_predicted_output(X_dataset, dataset_y, model, scaler)
    data_metric = metric(y_true_data, y_hat_data)
    print(f"{model_name} Data-set {metric_name}:", round(data_metric, 3))
  else:
    y_hat_data, y_true_data = y_true, y_hat
    data_metric = metric(y_true_data, y_hat_data)
    print(f"{model_name} Data-set {metric_name}:", round(data_metric, 3))

  if X_train is not None:
    y_hat_train, y_true_train = denormalize_real_and_predicted_output(X_train, train_y, model, scaler)
    train_metric = metric(y_true_train, y_hat_train)
    print(f"{model_name} Train-set {metric_name}:", round(train_metric, 3))
  else:
    y_hat_train, y_true_train, train_metric = None, None, None

  if X_test is not None:
    y_hat_test, y_true_test = denormalize_real_and_predicted_output(X_test, test_y, model, scaler)
    test_metric = metric(y_true_test, y_hat_test)
    print(f"{model_name} Test-set {metric_name}:", round(test_metric, 3))
  else:
    y_hat_test, y_true_test, test_metric = None, None, None

  return data_metric, train_metric, test_metric, y_hat_data, y_true_data, y_hat_train, y_true_train, y_hat_test, y_true_test

def adjusted_metrics_compute(metric_name, model_name, y_hat_test, y_true_test):

  if metric_name.lower() == "rmse":
    metric = rmse
  elif metric_name.lower() == "mae":
    metric = mae
  elif metric_name.lower() == "mape":
    metric = mape
  else:
    metric = r2_score

  test_metric = metric(y_true_test, y_hat_test)
  print(f"{model_name} Test-set {metric_name}:", round(test_metric, 3))

  return test_metric

def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
  '''
  Converts a time series into supervised learning
  '''

  n_vars = 1 if type(data) is list else data.shape[1]
  df = pd.DataFrame(data)
  cols, names = list(), list()
  for i in range(n_in, 0, -1):
    cols.append(df.shift(i))
    names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
  for i in range(0, n_out):
    cols.append(df.shift(-i))
    if i == 0:
      names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
    else:
      names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
  agg = pd.concat(cols, axis=1)
  agg.columns = names
  if dropnan:
    agg.dropna(inplace=True)
  return agg

def plot_curves(title, neural_model, set_type, denorm_y_pred, denorm_y_test, rmse, mae, mape, r_score):
  pred_df = pd.DataFrame({'Real Y' : denorm_y_test, 'Predicted Y' : denorm_y_pred})

  pred_title = title + "RMSE: "+str(np.round(rmse,3))+' - MAE: '+str(np.round(mae,3))+' - RSCORE: '+str(np.round(r_score,3)) + ' - MAPE: '+str(np.round(mape,3))

  plt.figure()												# generate a new window
  plt.plot(denorm_y_pred, label='Predicted Y', color = 'red')
  plt.plot(denorm_y_test, label='Real Y', color = 'blue')
  plt.legend()
  plt.title(pred_title)
  plt.savefig(f"./{neural_model}_forecasting_model_{set_type}_set_predictions.png", dpi = 600)
  plt.close()

  fig = px.line(pd.DataFrame(pred_df), title=pred_title,
                  labels={
                      "index": "Set Data Point",
                      "value": "Real Y / Predicted Y",
                      "variable": "Real / Predicted"
                  })
  fig.write_html(f"./{neural_model}_forecasting_model_{set_type}_set_predictions.html")
  fig.show()

# **Deep Learning Functions Definition**

In [106]:
def model_definition(X_train, summary = False, neural_cells = 50):
  rnn_input_shape = (X_train.shape[1], X_train.shape[2])
  model = Sequential()
  if neural_model == "GRU":
    model.add(GRU(neural_cells, input_shape = rnn_input_shape))
  elif neural_model == "LSTM":
    model.add(LSTM(neural_cells, input_shape = rnn_input_shape))
  elif neural_model == "BiLSTM":
    model.add(Bidirectional(LSTM(neural_cells), input_shape = rnn_input_shape))
  model.add(Dense(1, activation = "sigmoid"))
  model.compile(loss='mae', optimizer='adam')
  if summary is True:
    model.summary()

  return(model)

def auto_rnn(y_train, neural_model, k, epochs, verbose = 0, neural_cells = 50):
  #  Preprocessing for Deep Learning
  y_train_dl = np.reshape(y_train, (len(y_train), 1))
  y_train_dl.shape

  # Transformation from an unsupervised Time Series to a Supervised Dataset suitable for Deep Learning Supervised Models such as LSTM, GRU, Transformers, etc.
  supervised_full_dataset_df = series_to_supervised(y_train_dl, 1, 1)

  # Normalization
  scaler = MinMaxScaler(feature_range=(0, 1))
  supervised_scaled_full_dataset_df_values = scaler.fit_transform(supervised_full_dataset_df.values)

  # Train-Test Split
  X_dataset = supervised_scaled_full_dataset_df_values[:,:-1]
  y_dataset = supervised_scaled_full_dataset_df_values[:,-1]
  X_train, X_test, y_train, y_test = train_test_split(X_dataset, y_dataset, test_size=0.20, shuffle = False)  # Shuffle = False since we do not have to unstructure temporal dependencies in time series
  X_dataset = X_dataset.reshape((X_dataset.shape[0], 1, X_dataset.shape[1]))
  X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
  X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

  if k == 0:
    model = model_definition(X_train, neural_cells)
  else:
    model = load_model(f"./{neural_model}_{epochs}_epochs_{neural_cells}_neural_cells_last.keras")

  history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test), verbose=verbose, shuffle=False)

  model.save(f"./{neural_model}_{epochs}_epochs_{neural_cells}_neural_cells_last.keras")

  return model, scaler, X_train, y_train, X_test, y_test, X_dataset, y_dataset

def denormalize_real_and_predicted_output(X_test, y_test, forecasting_model, scaler):
  y_pred = forecasting_model.predict(X_test, verbose = 0)
  X_test_reshaped = X_test.reshape((X_test.shape[0], X_test.shape[2]))
  X_test_reshaped.shape

  denorm_X_test = np.concatenate((X_test_reshaped, y_pred), axis=1)
  denorm_X_test = scaler.inverse_transform(denorm_X_test)
  denorm_y_pred = denorm_X_test[:, denorm_X_test.shape[1]-1]

  y_test = y_test.reshape((len(y_test), 1))

  denorm_X_test = np.concatenate((X_test_reshaped, y_test), axis=1)
  denorm_X_test = scaler.inverse_transform(denorm_X_test)
  denorm_y_test = denorm_X_test[:, denorm_X_test.shape[1]-1]

  return(denorm_y_pred,denorm_y_test)

def denormalize_and_predicted_output(X_test, forecasting_model, scaler):
  X_test = np.reshape(X_test, (len(X_test), 1))
  y_pred = fit.predict(X_test, verbose = 0)
  denorm_y_pred = np.concatenate((X_test, y_pred), axis=1)
  denorm_y_pred = scaler.inverse_transform(denorm_y_pred)

  return denorm_y_pred[:, denorm_y_pred.shape[1]-1], denorm_y_pred[:, denorm_y_pred.shape[1]-1][-1]

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    #Attention
    x = MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(inputs, inputs)
    x = Dropout(dropout)(x)
    res = x + inputs

    # Feed Forward Part
    x = Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(x)
    x = Dropout(dropout)(x)
    x = Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    return x + res

def build_model(
    input_shape,
    head_size,
    num_heads,
    ff_dim,
    num_transformer_blocks,
    mlp_units,
    dropout=0,
    mlp_dropout=0,
):
    inputs = Input(shape=input_shape)
    x = inputs
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = GlobalAveragePooling1D(data_format="channels_first")(x)
    for dim in mlp_units:
        x = Dense(dim, activation="relu")(x)
        x = Dropout(mlp_dropout)(x)
    outputs = Dense(1)(x)
    return Model(inputs, outputs)

def model_vt_definition(X_train, summary = False, num_attention_heads = 4):
  input_shape = (X_train.shape[1], X_train.shape[2])

  model_transf = build_model(
            input_shape,
            head_size=128,
            num_heads = num_attention_heads,
            ff_dim=6,
            num_transformer_blocks=6,
            mlp_units=[250],
            mlp_dropout=0.3,
            dropout=0.25,
        )

  model_transf.compile(
            loss="mae",
            optimizer=Adam(learning_rate=1e-4),
        )

  if summary is True:
    model_transf.summary()

  return model_transf

def auto_vt(y_train, k, epochs, verbose = 0, num_attention_heads = 4):
  #  Preprocessing for Deep Learning
  y_train_dl = np.reshape(y_train, (len(y_train), 1))
  y_train_dl.shape

  # Transformation from an unsupervised Time Series to a Supervised Dataset suitable for Deep Learning Supervised Models such as LSTM, GRU, Transformers, etc.
  supervised_full_dataset_df = series_to_supervised(y_train_dl, 1, 1)

  # Normalization
  scaler = MinMaxScaler(feature_range=(0, 1))
  supervised_scaled_full_dataset_df_values = scaler.fit_transform(supervised_full_dataset_df.values)

  # Train-Test Split
  X_dataset = supervised_scaled_full_dataset_df_values[:,:-1]
  y_dataset = supervised_scaled_full_dataset_df_values[:,-1]
  X_train, X_test, y_train, y_test = train_test_split(X_dataset, y_dataset, test_size=0.20, shuffle = False)  # Shuffle = False since we do not have to unstructure temporal dependencies in time series
  X_dataset = X_dataset.reshape((X_dataset.shape[0], 1, X_dataset.shape[1]))
  X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
  X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

  if k == 0:
    model = model_vt_definition(X_train, num_attention_heads)
  else:
    model = load_model(f"./vanilla_transformer_{epochs}_epochs_{num_attention_heads}_num_attention_heads_last.keras")

  history_transf=model.fit(
            X_train,
            y_train,
            validation_data = (X_test, y_test),
            epochs = epochs,
            batch_size = batch_size,
            verbose = verbose,
            shuffle = False,
            )

  model.save(f"./vanilla_transformer_{epochs}_epochs_{num_attention_heads}_num_attention_heads_last.keras")

  return model, scaler, X_train, y_train, X_test, y_test, X_dataset, y_dataset

# **LSTM, GRU, BiLSTM**

In [107]:
start_time = timeit.default_timer()
y_train = y
rnn_model, scaler, X_train, train_y, X_test, test_y, X_dataset, dataset_y = auto_rnn(y_train, neural_model, 0, epochs, verbose = 1, neural_cells = neural_cells)
print("Elapsed LSTM Time: ", timeit.default_timer() - start_time)

Epoch 1/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 145ms/step - loss: 0.3540 - val_loss: 0.4852
Epoch 2/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 0.3515 - val_loss: 0.4815
Epoch 3/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.3489 - val_loss: 0.4776
Epoch 4/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.3462 - val_loss: 0.4736
Epoch 5/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.3435 - val_loss: 0.4695
Epoch 6/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.3407 - val_loss: 0.4652
Epoch 7/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.3378 - val_loss: 0.4606
Epoch 8/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3347 - val_loss: 0.4558
Epoch 9/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3315 - val_loss: 0.4507
Epoch 10/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.3281 - val_loss: 0.4454
Epoch 11/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3246 - val_loss: 0.4398
Epoch 12/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.3209 - val_loss: 0.4338
Epoch 13/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.3170 - val_loss: 0.4276
Epoch 14/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3129 - val_loss: 0.4209
Epoch 15/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.3086 - val_loss: 0.4140
Epoch 16/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3041 - val_loss: 0.4067
Epoch 17/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.2994 - val_loss: 0.3990
Epoch 18/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.2945 - val_loss: 0.3909
Epoch 19/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.2894 - val_loss: 0.3825
Epoch 20/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.2840 - val_loss: 0.3738
Epoch 21/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.2786 - val_loss: 0.3647
Epoch 22/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2729 - val_loss: 0.3554
Epoch 23/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2672 - val_loss: 0.3458
Epoch 24/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2613 - val_loss: 0.3360
Epoch 25/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.2554 - val_loss: 0.3260
Epoch 26/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2494 - val_loss: 0.3159
Epoch 27/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.2433 - val_loss: 0.3056
Epoch 28/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.2373 - val_loss: 0.2953
Epoch 29/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.2314 - val_loss: 0.2850
Epoch 30/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2255 - val_loss: 0.2747
Epoch 31/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2198 - val_loss: 0.2646
Epoch 32/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.2141 - val_loss: 0.2545
Epoch 33/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.2086 - val_loss: 0.2446
Epoch 34/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - loss: 0.2032 - val_loss: 0.2349
Epoch 35/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.1981 - val_loss: 0.2254
Epoch 36/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.1931 - val_loss: 0.2162
Epoch 37/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step - loss: 0.1883 - val_loss: 0.2072
Epoch 38/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 85ms/step - loss: 0.1838 - val_loss: 0.1987
Epoch 39/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 0.1796 - val_loss: 0.1905
Epoch 40/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.1756 - val_loss: 0.1827
Epoch 41/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.1719 - val_loss: 0.1752
Epoch 42/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.1684 - val_loss: 0.1682
Epoch 43/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.1652 - val_loss: 0.1616
Epoch 44/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.1622 - val_loss: 0.1554
Epoch 45/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - loss: 0.1597 - val_loss: 0.1497
Epoch 46/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.1574 - val_loss: 0.1446
Epoch 47/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.1555 - val_loss: 0.1400
Epoch 48/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1538 - val_loss: 0.1359
Epoch 49/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1522 - val_loss: 0.1322
Epoch 50/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1507 - val_loss: 0.1288
Epoch 51/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.1494 - val_loss: 0.1257
Epoch 52/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1481 - val_loss: 0.1229
Epoch 53/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.1468 - val_loss: 0.1203
Epoch 54/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1456 - val_loss: 0.1179
Epoch 55/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1444 - val_loss: 0.1157
Epoch 56/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1433 - val_loss: 0.1137
Epoch 57/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1422 - val_loss: 0.1119
Epoch 58/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.1411 - val_loss: 0.1103
Epoch 59/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.1400 - val_loss: 0.1089
Epoch 60/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1389 - val_loss: 0.1076
Epoch 61/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1378 - val_loss: 0.1063
Epoch 62/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.1366 - val_loss: 0.1052
Epoch 63/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1355 - val_loss: 0.1041
Epoch 64/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.1343 - val_loss: 0.1032
Epoch 65/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1332 - val_loss: 0.1022
Epoch 66/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1320 - val_loss: 0.1014
Epoch 67/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.1308 - val_loss: 0.1006
Epoch 68/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1295 - val_loss: 0.0998
Epoch 69/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1283 - val_loss: 0.0991
Epoch 70/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.1270 - val_loss: 0.0984
Epoch 71/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.1256 - val_loss: 0.0978
Epoch 72/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1243 - val_loss: 0.0972
Epoch 73/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.1229 - val_loss: 0.0966
Epoch 74/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.1215 - val_loss: 0.0960
Epoch 75/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.1201 - val_loss: 0.0955
Epoch 76/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.1186 - val_loss: 0.0950
Epoch 77/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.1171 - val_loss: 0.0945
Epoch 78/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.1155 - val_loss: 0.0940
Epoch 79/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.1140 - val_loss: 0.0936
Epoch 80/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1123 - val_loss: 0.0931
Epoch 81/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.1107 - val_loss: 0.0927
Epoch 82/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1090 - val_loss: 0.0923
Epoch 83/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.1072 - val_loss: 0.0919
Epoch 84/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.1054 - val_loss: 0.0915
Epoch 85/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.1036 - val_loss: 0.0911
Epoch 86/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - loss: 0.1017 - val_loss: 0.0906
Epoch 87/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0998 - val_loss: 0.0902
Epoch 88/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0978 - val_loss: 0.0898
Epoch 89/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0958 - val_loss: 0.0893
Epoch 90/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 76ms/step - loss: 0.0937 - val_loss: 0.0888
Epoch 91/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0916 - val_loss: 0.0884
Epoch 92/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 87ms/step - loss: 0.0895 - val_loss: 0.0879
Epoch 93/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 92ms/step - loss: 0.0873 - val_loss: 0.0874
Epoch 94/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - loss: 0.0851 - val_loss: 0.0869
Epoch 95/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - loss: 0.0828 - val_loss: 0.0864
Epoch 96/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 121ms/step - loss: 0.0805 - val_loss: 0.0858
Epoch 97/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0781 - val_loss: 0.0852
Epoch 98/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0757 - val_loss: 0.0846
Epoch 99/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0733 - val_loss: 0.0839
Epoch 100/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0708 - val_loss: 0.0833
Epoch 101/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - loss: 0.0683 - val_loss: 0.0826
Epoch 102/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 146ms/step - loss: 0.0658 - val_loss: 0.0818
Epoch 103/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - loss: 0.0632 - val_loss: 0.0811
Epoch 104/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0607 - val_loss: 0.0803
Epoch 105/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0581 - val_loss: 0.0796
Epoch 106/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0555 - val_loss: 0.0788
Epoch 107/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - loss: 0.0528 - val_loss: 0.0781
Epoch 108/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.0502 - val_loss: 0.0772
Epoch 109/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0476 - val_loss: 0.0764
Epoch 110/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0450 - val_loss: 0.0755
Epoch 111/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0424 - val_loss: 0.0746
Epoch 112/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0399 - val_loss: 0.0736
Epoch 113/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0376 - val_loss: 0.0725
Epoch 114/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0358 - val_loss: 0.0712
Epoch 115/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0344 - val_loss: 0.0697
Epoch 116/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0333 - val_loss: 0.0680
Epoch 117/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0326 - val_loss: 0.0663
Epoch 118/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0320 - val_loss: 0.0647
Epoch 119/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0316 - val_loss: 0.0632
Epoch 120/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0313 - val_loss: 0.0619
Epoch 121/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0311 - val_loss: 0.0609
Epoch 122/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0309 - val_loss: 0.0599
Epoch 123/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0308 - val_loss: 0.0591
Epoch 124/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0306 - val_loss: 0.0584
Epoch 125/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0305 - val_loss: 0.0578
Epoch 126/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0305 - val_loss: 0.0572
Epoch 127/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0304 - val_loss: 0.0566
Epoch 128/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0303 - val_loss: 0.0561
Epoch 129/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0303 - val_loss: 0.0556
Epoch 130/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0302 - val_loss: 0.0552
Epoch 131/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0302 - val_loss: 0.0547
Epoch 132/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0301 - val_loss: 0.0543
Epoch 133/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0301 - val_loss: 0.0538
Epoch 134/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0300 - val_loss: 0.0534
Epoch 135/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0300 - val_loss: 0.0530
Epoch 136/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0300 - val_loss: 0.0527
Epoch 137/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0300 - val_loss: 0.0523
Epoch 138/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0299 - val_loss: 0.0520
Epoch 139/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0299 - val_loss: 0.0518
Epoch 140/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0299 - val_loss: 0.0515
Epoch 141/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0299 - val_loss: 0.0513
Epoch 142/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0298 - val_loss: 0.0511
Epoch 143/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0298 - val_loss: 0.0509
Epoch 144/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0298 - val_loss: 0.0507
Epoch 145/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0298 - val_loss: 0.0506
Epoch 146/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0297 - val_loss: 0.0504
Epoch 147/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0297 - val_loss: 0.0503
Epoch 148/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0297 - val_loss: 0.0502
Epoch 149/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0296 - val_loss: 0.0500
Epoch 150/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0296 - val_loss: 0.0499
Epoch 151/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0296 - val_loss: 0.0498
Epoch 152/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0296 - val_loss: 0.0498
Epoch 153/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.0295 - val_loss: 0.0497
Epoch 154/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0295 - val_loss: 0.0496
Epoch 155/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0295 - val_loss: 0.0495
Epoch 156/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0294 - val_loss: 0.0493
Epoch 157/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0294 - val_loss: 0.0492
Epoch 158/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0294 - val_loss: 0.0491
Epoch 159/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0294 - val_loss: 0.0491
Epoch 160/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0293 - val_loss: 0.0490
Epoch 161/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0293 - val_loss: 0.0489
Epoch 162/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0293 - val_loss: 0.0487
Epoch 163/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0293 - val_loss: 0.0486
Epoch 164/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0292 - val_loss: 0.0486
Epoch 165/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 85ms/step - loss: 0.0292 - val_loss: 0.0485
Epoch 166/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0292 - val_loss: 0.0484
Epoch 167/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0292 - val_loss: 0.0484
Epoch 168/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0291 - val_loss: 0.0483
Epoch 169/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0291 - val_loss: 0.0482
Epoch 170/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0291 - val_loss: 0.0482
Epoch 171/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0290 - val_loss: 0.0481
Epoch 172/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0290 - val_loss: 0.0480
Epoch 173/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0290 - val_loss: 0.0480
Epoch 174/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0290 - val_loss: 0.0479
Epoch 175/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.0289 - val_loss: 0.0478
Epoch 176/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0289 - val_loss: 0.0478
Epoch 177/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.0289 - val_loss: 0.0477
Epoch 178/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0289 - val_loss: 0.0477
Epoch 179/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0288 - val_loss: 0.0476
Epoch 180/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0288 - val_loss: 0.0476
Epoch 181/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0288 - val_loss: 0.0475
Epoch 182/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0288 - val_loss: 0.0475
Epoch 183/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0287 - val_loss: 0.0474
Epoch 184/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0287 - val_loss: 0.0474
Epoch 185/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0287 - val_loss: 0.0474
Epoch 186/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0286 - val_loss: 0.0473
Epoch 187/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0286 - val_loss: 0.0473
Epoch 188/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0286 - val_loss: 0.0472
Epoch 189/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0286 - val_loss: 0.0472
Epoch 190/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0285 - val_loss: 0.0471
Epoch 191/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0285 - val_loss: 0.0471
Epoch 192/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0285 - val_loss: 0.0470
Epoch 193/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0285 - val_loss: 0.0470
Epoch 194/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0284 - val_loss: 0.0469
Epoch 195/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0284 - val_loss: 0.0469
Epoch 196/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0284 - val_loss: 0.0468
Epoch 197/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0283 - val_loss: 0.0468
Epoch 198/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0283 - val_loss: 0.0467
Epoch 199/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0283 - val_loss: 0.0466
Epoch 200/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0283 - val_loss: 0.0466
Epoch 201/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0282 - val_loss: 0.0465
Epoch 202/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0282 - val_loss: 0.0464
Epoch 203/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0282 - val_loss: 0.0464
Epoch 204/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0282 - val_loss: 0.0464
Epoch 205/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0282 - val_loss: 0.0463
Epoch 206/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0281 - val_loss: 0.0463
Epoch 207/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0281 - val_loss: 0.0463
Epoch 208/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0281 - val_loss: 0.0462
Epoch 209/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0280 - val_loss: 0.0462
Epoch 210/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0280 - val_loss: 0.0462
Epoch 211/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0280 - val_loss: 0.0462
Epoch 212/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0280 - val_loss: 0.0461
Epoch 213/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0279 - val_loss: 0.0461
Epoch 214/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0279 - val_loss: 0.0461
Epoch 215/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0279 - val_loss: 0.0460
Epoch 216/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0279 - val_loss: 0.0460
Epoch 217/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0278 - val_loss: 0.0459
Epoch 218/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0278 - val_loss: 0.0459
Epoch 219/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0278 - val_loss: 0.0458
Epoch 220/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0278 - val_loss: 0.0458
Epoch 221/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0278 - val_loss: 0.0457
Epoch 222/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0277 - val_loss: 0.0457
Epoch 223/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0277 - val_loss: 0.0456
Epoch 224/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.0277 - val_loss: 0.0456
Epoch 225/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.0277 - val_loss: 0.0455
Epoch 226/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0277 - val_loss: 0.0455
Epoch 227/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0276 - val_loss: 0.0454
Epoch 228/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0276 - val_loss: 0.0453
Epoch 229/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0276 - val_loss: 0.0453
Epoch 230/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0276 - val_loss: 0.0452
Epoch 231/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0276 - val_loss: 0.0452
Epoch 232/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0275 - val_loss: 0.0451
Epoch 233/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0275 - val_loss: 0.0451
Epoch 234/250

## **LSTM, GRU, BiLSTM Performance Evaluation**

In [108]:
for metric in ["RMSE", "MAE", "MAPE", "R2-SCORE"]:
  data_metric_rnn, train_metric_rnn, test_metric_rnn, y_hat_data_rnn, y_true_data_rnn, y_hat_train_rnn, y_true_train_rnn, y_hat_test_rnn, y_true_test_rnn = metrics_compute(metric, neural_model, rnn_model, scaler, X_dataset, dataset_y, X_train, train_y, X_test, test_y)
  if metric == "RMSE":
    data_rmse_rnn = data_metric_rnn
    train_rmse_rnn = train_metric_rnn
    test_rmse_rnn = test_metric_rnn
  elif metric == "MAE":
    data_mae_rnn = data_metric_rnn
    train_mae_rnn = train_metric_rnn
    test_mae_rnn = test_metric_rnn
  elif metric == "MAPE":
    data_mape_rnn = data_metric_rnn
    train_mape_rnn = train_metric_rnn
    test_mape_rnn = test_metric_rnn
  else:
    data_r2_score_rnn = data_metric_rnn
    train_r2_score_rnn = train_metric_rnn
    test_r2_score_rnn = test_metric_rnn

  print("\n")

LSTM Data-set RMSE: 13.8
LSTM Train-set RMSE: 12.64
LSTM Test-set RMSE: 17.698


LSTM Data-set MAE: 12.149
LSTM Train-set MAE: 10.788
LSTM Test-set MAE: 17.596


LSTM Data-set MAPE: 366933950476077.94
LSTM Train-set MAPE: 458667438095096.0
LSTM Test-set MAPE: 6.355


LSTM Data-set R2-SCORE: 0.979
LSTM Train-set R2-SCORE: 0.984
LSTM Test-set R2-SCORE: -38.832

## **Real and Predicted Curves Visualization for RNN**

## **Dataset**

In [109]:
plot_curves("Dataset - ", neural_model, "data", y_hat_data_rnn, y_true_data_rnn, data_rmse_rnn, data_mae_rnn, data_mape_rnn, data_r2_score_rnn)

## **Trainset**

In [110]:
plot_curves("Train-set - ", neural_model, "train", y_hat_train_rnn, y_true_train_rnn, train_rmse_rnn, train_mae_rnn, train_mape_rnn, train_r2_score_rnn)

## **Testset**

In [113]:
  plot_curves("Test-set - ", neural_model, "test", y_hat_test_rnn, y_true_test_rnn, test_rmse_rnn, test_mae_rnn, test_mape_rnn, test_r2_score_rnn)

# **Vanilla Transformer**

In [114]:
start_time = timeit.default_timer()
y_train = y
vt_model, scaler, X_train, train_y, X_test, test_y, X_dataset, dataset_y = auto_vt(y_train, 0, epochs, verbose = 1, num_attention_heads = num_attention_heads)
print("Elapsed LSTM Time: ", timeit.default_timer() - start_time)

Epoch 1/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 3s/step - loss: 0.2401 - val_loss: 0.0063
Epoch 2/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.2225 - val_loss: 0.0089
Epoch 3/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2116 - val_loss: 0.0199
Epoch 4/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2016 - val_loss: 0.0324
Epoch 5/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1972 - val_loss: 0.0432
Epoch 6/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.1929 - val_loss: 0.0507
Epoch 7/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1877 - val_loss: 0.0553
Epoch 8/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1849 - val_loss: 0.0582
Epoch 9/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1830 - val_loss: 0.0600
Epoch 10/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1817 - val_loss: 0.0612
Epoch 11/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1799 - val_loss: 0.0621
Epoch 12/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1770 - val_loss: 0.0627
Epoch 13/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1761 - val_loss: 0.0633
Epoch 14/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1738 - val_loss: 0.0643
Epoch 15/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1728 - val_loss: 0.0650
Epoch 16/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1726 - val_loss: 0.0653
Epoch 17/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1704 - val_loss: 0.0657
Epoch 18/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.1700 - val_loss: 0.0659
Epoch 19/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1696 - val_loss: 0.0659
Epoch 20/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1654 - val_loss: 0.0658
Epoch 21/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1652 - val_loss: 0.0652
Epoch 22/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1607 - val_loss: 0.0651
Epoch 23/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1597 - val_loss: 0.0651
Epoch 24/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.1552 - val_loss: 0.0644
Epoch 25/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.1519 - val_loss: 0.0623
Epoch 26/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.1448 - val_loss: 0.0604
Epoch 27/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.1366 - val_loss: 0.0576
Epoch 28/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.1321 - val_loss: 0.0532
Epoch 29/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1229 - val_loss: 0.0494
Epoch 30/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.1214 - val_loss: 0.0442
Epoch 31/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1215 - val_loss: 0.0430
Epoch 32/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.1200 - val_loss: 0.0431
Epoch 33/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1194 - val_loss: 0.0428
Epoch 34/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1167 - val_loss: 0.0425
Epoch 35/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.1123 - val_loss: 0.0417
Epoch 36/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1183 - val_loss: 0.0412
Epoch 37/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1135 - val_loss: 0.0410
Epoch 38/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1107 - val_loss: 0.0408
Epoch 39/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1051 - val_loss: 0.0401
Epoch 40/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1052 - val_loss: 0.0406
Epoch 41/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1073 - val_loss: 0.0373
Epoch 42/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1048 - val_loss: 0.0366
Epoch 43/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1031 - val_loss: 0.0364
Epoch 44/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1032 - val_loss: 0.0356
Epoch 45/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1013 - val_loss: 0.0390
Epoch 46/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1052 - val_loss: 0.0356
Epoch 47/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0990 - val_loss: 0.0338
Epoch 48/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1027 - val_loss: 0.0349
Epoch 49/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0993 - val_loss: 0.0356
Epoch 50/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0973 - val_loss: 0.0320
Epoch 51/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0988 - val_loss: 0.0330
Epoch 52/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0962 - val_loss: 0.0343
Epoch 53/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0978 - val_loss: 0.0320
Epoch 54/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0943 - val_loss: 0.0329
Epoch 55/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0977 - val_loss: 0.0324
Epoch 56/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0956 - val_loss: 0.0330
Epoch 57/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0961 - val_loss: 0.0305
Epoch 58/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0960 - val_loss: 0.0342
Epoch 59/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0928 - val_loss: 0.0324
Epoch 60/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0929 - val_loss: 0.0336
Epoch 61/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0949 - val_loss: 0.0319
Epoch 62/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0902 - val_loss: 0.0315
Epoch 63/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0910 - val_loss: 0.0354
Epoch 64/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0905 - val_loss: 0.0344
Epoch 65/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0890 - val_loss: 0.0336
Epoch 66/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0884 - val_loss: 0.0325
Epoch 67/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0874 - val_loss: 0.0378
Epoch 68/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0899 - val_loss: 0.0354
Epoch 69/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0898 - val_loss: 0.0333
Epoch 70/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0903 - val_loss: 0.0314
Epoch 71/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0889 - val_loss: 0.0320
Epoch 72/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0863 - val_loss: 0.0336
Epoch 73/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0844 - val_loss: 0.0345
Epoch 74/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0885 - val_loss: 0.0323
Epoch 75/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0836 - val_loss: 0.0311
Epoch 76/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0875 - val_loss: 0.0325
Epoch 77/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0865 - val_loss: 0.0328
Epoch 78/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0824 - val_loss: 0.0340
Epoch 79/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0805 - val_loss: 0.0297
Epoch 80/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0831 - val_loss: 0.0316
Epoch 81/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0855 - val_loss: 0.0335
Epoch 82/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0825 - val_loss: 0.0314
Epoch 83/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0824 - val_loss: 0.0304
Epoch 84/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0837 - val_loss: 0.0316
Epoch 85/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0825 - val_loss: 0.0351
Epoch 86/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0840 - val_loss: 0.0312
Epoch 87/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0787 - val_loss: 0.0363
Epoch 88/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0794 - val_loss: 0.0305
Epoch 89/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0827 - val_loss: 0.0279
Epoch 90/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0809 - val_loss: 0.0324
Epoch 91/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0755 - val_loss: 0.0307
Epoch 92/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0804 - val_loss: 0.0334
Epoch 93/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0799 - val_loss: 0.0289
Epoch 94/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0781 - val_loss: 0.0298
Epoch 95/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0781 - val_loss: 0.0287
Epoch 96/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0745 - val_loss: 0.0311
Epoch 97/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0746 - val_loss: 0.0272
Epoch 98/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0733 - val_loss: 0.0302
Epoch 99/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0758 - val_loss: 0.0281
Epoch 100/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0782 - val_loss: 0.0246
Epoch 101/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0703 - val_loss: 0.0256
Epoch 102/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0720 - val_loss: 0.0247
Epoch 103/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0741 - val_loss: 0.0236
Epoch 104/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0734 - val_loss: 0.0239
Epoch 105/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0733 - val_loss: 0.0234
Epoch 106/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0680 - val_loss: 0.0220
Epoch 107/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0714 - val_loss: 0.0234
Epoch 108/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0715 - val_loss: 0.0203
Epoch 109/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0740 - val_loss: 0.0239
Epoch 110/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0672 - val_loss: 0.0212
Epoch 111/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.0681 - val_loss: 0.0241
Epoch 112/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.0688 - val_loss: 0.0234
Epoch 113/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 144ms/step - loss: 0.0682 - val_loss: 0.0199
Epoch 114/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0701 - val_loss: 0.0229
Epoch 115/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 90ms/step - loss: 0.0694 - val_loss: 0.0215
Epoch 116/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - loss: 0.0690 - val_loss: 0.0230
Epoch 117/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0664 - val_loss: 0.0225
Epoch 118/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0644 - val_loss: 0.0203
Epoch 119/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0689 - val_loss: 0.0224
Epoch 120/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0681 - val_loss: 0.0219
Epoch 121/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0689 - val_loss: 0.0224
Epoch 122/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0662 - val_loss: 0.0192
Epoch 123/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0643 - val_loss: 0.0217
Epoch 124/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0638 - val_loss: 0.0211
Epoch 125/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0636 - val_loss: 0.0206
Epoch 126/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0717 - val_loss: 0.0215
Epoch 127/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0664 - val_loss: 0.0195
Epoch 128/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0629 - val_loss: 0.0190
Epoch 129/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0642 - val_loss: 0.0241
Epoch 130/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0652 - val_loss: 0.0191
Epoch 131/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0659 - val_loss: 0.0196
Epoch 132/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0630 - val_loss: 0.0208
Epoch 133/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0661 - val_loss: 0.0195
Epoch 134/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0643 - val_loss: 0.0201
Epoch 135/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0609 - val_loss: 0.0218
Epoch 136/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0654 - val_loss: 0.0216
Epoch 137/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0643 - val_loss: 0.0183
Epoch 138/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0633 - val_loss: 0.0214
Epoch 139/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0658 - val_loss: 0.0206
Epoch 140/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0625 - val_loss: 0.0217
Epoch 141/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0630 - val_loss: 0.0209
Epoch 142/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0622 - val_loss: 0.0218
Epoch 143/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0610 - val_loss: 0.0192
Epoch 144/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0657 - val_loss: 0.0198
Epoch 145/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0621 - val_loss: 0.0189
Epoch 146/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0555 - val_loss: 0.0202
Epoch 147/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0639 - val_loss: 0.0170
Epoch 148/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0604 - val_loss: 0.0207
Epoch 149/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0583 - val_loss: 0.0183
Epoch 150/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0584 - val_loss: 0.0190
Epoch 151/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0621 - val_loss: 0.0198
Epoch 152/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0608 - val_loss: 0.0185
Epoch 153/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0591 - val_loss: 0.0161
Epoch 154/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0639 - val_loss: 0.0209
Epoch 155/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0629 - val_loss: 0.0165
Epoch 156/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0576 - val_loss: 0.0190
Epoch 157/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0588 - val_loss: 0.0189
Epoch 158/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0602 - val_loss: 0.0192
Epoch 159/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0610 - val_loss: 0.0198
Epoch 160/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0605 - val_loss: 0.0160
Epoch 161/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0581 - val_loss: 0.0206
Epoch 162/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0568 - val_loss: 0.0165
Epoch 163/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0599 - val_loss: 0.0170
Epoch 164/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0568 - val_loss: 0.0172
Epoch 165/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0585 - val_loss: 0.0191
Epoch 166/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0558 - val_loss: 0.0141
Epoch 167/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0558 - val_loss: 0.0169
Epoch 168/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0568 - val_loss: 0.0166
Epoch 169/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0578 - val_loss: 0.0148
Epoch 170/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0604 - val_loss: 0.0173
Epoch 171/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0561 - val_loss: 0.0181
Epoch 172/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0594 - val_loss: 0.0143
Epoch 173/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0587 - val_loss: 0.0197
Epoch 174/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0602 - val_loss: 0.0152
Epoch 175/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0563 - val_loss: 0.0154
Epoch 176/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0554 - val_loss: 0.0183
Epoch 177/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0583 - val_loss: 0.0191
Epoch 178/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0605 - val_loss: 0.0164
Epoch 179/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0557 - val_loss: 0.0159
Epoch 180/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0585 - val_loss: 0.0189
Epoch 181/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0559 - val_loss: 0.0143
Epoch 182/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0566 - val_loss: 0.0173
Epoch 183/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0584 - val_loss: 0.0158
Epoch 184/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0574 - val_loss: 0.0173
Epoch 185/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0605 - val_loss: 0.0184
Epoch 186/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0591 - val_loss: 0.0159
Epoch 187/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0554 - val_loss: 0.0155
Epoch 188/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0559 - val_loss: 0.0171
Epoch 189/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0606 - val_loss: 0.0161
Epoch 190/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0583 - val_loss: 0.0155
Epoch 191/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0552 - val_loss: 0.0178
Epoch 192/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0580 - val_loss: 0.0162
Epoch 193/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0586 - val_loss: 0.0182
Epoch 194/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0570 - val_loss: 0.0158
Epoch 195/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0573 - val_loss: 0.0169
Epoch 196/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0594 - val_loss: 0.0149
Epoch 197/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0575 - val_loss: 0.0163
Epoch 198/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0576 - val_loss: 0.0144
Epoch 199/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0560 - val_loss: 0.0169
Epoch 200/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0548 - val_loss: 0.0163
Epoch 201/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0560 - val_loss: 0.0189
Epoch 202/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0550 - val_loss: 0.0141
Epoch 203/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0542 - val_loss: 0.0142
Epoch 204/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0557 - val_loss: 0.0159
Epoch 205/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0539 - val_loss: 0.0140
Epoch 206/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0572 - val_loss: 0.0148
Epoch 207/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0529 - val_loss: 0.0141
Epoch 208/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0549 - val_loss: 0.0156
Epoch 209/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0542 - val_loss: 0.0137
Epoch 210/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0564 - val_loss: 0.0196
Epoch 211/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0553 - val_loss: 0.0135
Epoch 212/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0540 - val_loss: 0.0135
Epoch 213/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0585 - val_loss: 0.0159
Epoch 214/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0531 - val_loss: 0.0127
Epoch 215/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0567 - val_loss: 0.0128
Epoch 216/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0531 - val_loss: 0.0137
Epoch 217/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0571 - val_loss: 0.0153
Epoch 218/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0531 - val_loss: 0.0135
Epoch 219/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0513 - val_loss: 0.0151
Epoch 220/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0521 - val_loss: 0.0144
Epoch 221/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0532 - val_loss: 0.0145
Epoch 222/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0554 - val_loss: 0.0161
Epoch 223/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0557 - val_loss: 0.0152
Epoch 224/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0557 - val_loss: 0.0142
Epoch 225/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0503 - val_loss: 0.0156
Epoch 226/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0563 - val_loss: 0.0147
Epoch 227/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0534 - val_loss: 0.0137
Epoch 228/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0546 - val_loss: 0.0139
Epoch 229/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0508 - val_loss: 0.0138
Epoch 230/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0548 - val_loss: 0.0133
Epoch 231/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0540 - val_loss: 0.0131
Epoch 232/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0541 - val_loss: 0.0140
Epoch 233/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0539 - val_loss: 0.0133
Epoch 234/250

## **Vanilla Transformer Predictions Performance Evaluation**

In [115]:
for metric in ["RMSE", "MAE", "MAPE", "R2-SCORE"]:
  data_metric_vt, train_metric_vt, test_metric_vt, y_hat_data_vt, y_true_data_vt, y_hat_train_vt, y_true_train_vt, y_hat_test_vt, y_true_test_vt = metrics_compute(metric, "Vanilla Transformer", vt_model, scaler, X_dataset, dataset_y, X_train, train_y, X_test, test_y)
  if metric == "RMSE":
    data_rmse_vt = data_metric_vt
    train_rmse_vt = train_metric_vt
    test_rmse_vt = test_metric_vt
  elif metric == "MAE":
    data_mae_vt = data_metric_vt
    train_mae_vt = train_metric_vt
    test_mae_vt = test_metric_vt
  elif metric == "MAPE":
    data_mape_vt = data_metric_vt
    train_mape_vt = train_metric_vt
    test_mape_vt = test_metric_vt
  else:
    data_r2_score_vt = data_metric_vt
    train_r2_score_vt = train_metric_vt
    test_r2_score_vt = test_metric_vt

  print("\n")

Vanilla Transformer Data-set RMSE: 51.119
Vanilla Transformer Train-set RMSE: 57.069
Vanilla Transformer Test-set RMSE: 6.223


Vanilla Transformer Data-set MAE: 28.098
Vanilla Transformer Train-set MAE: 33.84
Vanilla Transformer Test-set MAE: 5.131


Vanilla Transformer Data-set MAPE: 236521834556050.9
Vanilla Transformer Train-set MAPE: 295652293195062.94
Vanilla Transformer Test-set MAPE: 2.531


Vanilla Transformer Data-set R2-SCORE: 0.71
Vanilla Transformer Train-set R2-SCORE: 0.672
Vanilla Transformer Test-set R2-SCORE: -3.926

## **Real and Predicted Curves Visualization for Vanilla Transformer**

## **Dataset**

In [116]:
plot_curves("Dataset - ", "vt", "data", y_hat_data_vt, y_true_data_vt, data_rmse_vt, data_mae_vt, data_mape_vt, data_r2_score_vt)

## **Trainset**

In [117]:
plot_curves("Train-set - ", "vt", "train", y_hat_train_vt, y_true_train_vt, train_rmse_vt, train_mae_vt, train_mape_vt, train_r2_score_vt)

## **Testset**

In [120]:
plot_curves("Test-set - ", "vt", "test", y_hat_test_vt, y_true_test_vt, test_rmse_vt, test_mae_vt, test_mape_vt, test_r2_score_vt)

# **Adjustment by Open-Weight LLMs**

In [121]:
# LLMs
llm_model_name = "meta-llama/Llama-3.2-1B-Instruct"             # ok, but not high, it's improving r2_score a little bit performance with penalty 1.3
#llm_model_name = "meta-llama/Llama-3.2-3B-Instruct"             # not ok, it's not generating any output, we need to work on hyperparameters
#llm_model_name = "meta-llama/Meta-Llama-3.1-8B-Instruct"        # not ok, less r2_score generated
#llm_model_name = "meta-llama/Meta-Llama-3.3-8B-Instruct"        # not working, maybe token
#llm_model_name = "Qwen/Qwen2.5-3B-Instruct"                      # not ok, a lot less r2_score generated
#llm_model_name = "Qwen/Qwen2.5-7B-Instruct"
#llm_model_name = "Qwen/Qwen2.5-14B-Instruct"
#llm_model_name = "Qwen/Qwen2.5-32B-Instruct"
#llm_model_name = "Qwen/Qwen2.5-72B-Instruct"
#llm_model_name = "mistralai/Mistral-7B-Instruct"

n_trials = 5
differential_corrections = True                   # In this case generate the corrections and not the absolute values of y_hat_test
improvement_delta = 0.07

In [122]:
y_true_train_vt_df = pd.DataFrame(y_true_train_vt)
y_hat_train_vt_df = pd.DataFrame(y_hat_train_vt)
y_hat_test_vt_df = pd.DataFrame(y_hat_test_vt)
y_true_test_vt_df = pd.DataFrame(y_true_test_vt)
y_true_train_vt_df.to_csv("./y_true_train_vt.csv")
y_hat_train_vt_df.to_csv("./y_hat_train_vt.csv")
y_hat_test_vt_df.to_csv("./y_hat_test_vt.csv")
y_true_test_vt_df.to_csv("./y_true_test_vt.csv")

In [125]:
start_time = timeit.default_timer()

for k in range(n_trials):

  train_y = y_true_train_vt.tolist()
  train_pred = y_hat_train_vt.tolist()
  test_pred = y_hat_test_vt.tolist()

  tokenizer = AutoTokenizer.from_pretrained(llm_model_name)
  tokenizer.pad_token = tokenizer.eos_token
  llm_model = AutoModelForCausalLM.from_pretrained(llm_model_name, dtype=torch.float16, device_map="auto")

  # few-shot learning
  examples = []

  for y_true, y_pred in list(zip(train_y, train_pred)):
      examples.append(
          f"Model prediction: {y_pred:.5f}\n"
          f"Correct real value: {y_true:.5f}\n"
      )

  system_instruction = (
      "You are an expert model in time series correction. "
      "You will be shown a model's predictions and the correct real values. "
      "Learn the type of error and how to correct it. "
      "Then you will receive only new predictions and must return "
      "the corrected versions, one per line, NUMBERS ONLY."
  )

  base_prompt = (
      f"{system_instruction}\n\n"
      "CORRECTION EXAMPLES:\n"
      f"{"\n".join(examples)}\n"
  )

  test_values = "\n".join([f"{v:.5f}" for v in test_pred])

  test_prompt = (
      base_prompt +
      "NOW CORRECT THESE NEW PREDICTIONS\n"
      "Model predictions to correct:\n"
      f"{test_values}\n\n"
      "Corrected values:"
  )

  inputs = tokenizer(test_prompt, return_tensors="pt").to(llm_model.device)


  if n_trials == 1:
    with torch.no_grad():
        output = llm_model.generate(
            **inputs,
            max_new_tokens=4096,
            temperature=0.2,
            repetition_penalty=1.3,
            do_sample=False
        )
  else:
    with torch.no_grad():
        output = llm_model.generate(
            **inputs,
            max_new_tokens=4096,
            temperature = random.uniform(0.0, 1.2),
            repetition_penalty = random.uniform(1.0, 1.6),
            do_sample=False
        )

  decoded = tokenizer.decode(output[0], skip_special_tokens=True)

  corrected_part = decoded.split("Corrected values:")[-1].strip()

  numbers = re.findall(r"-?\d+\.\d+|-?\d+", corrected_part)
  numbers = [float(n) for n in numbers]
  numbers = np.array(numbers)
  if len(numbers) < len(test_pred):
    y_hat_test_vt_adjusted = numbers
    y_true_test_vt_for_adj = y_true_test_vt[0:len(numbers)]
  else:
    y_hat_test_vt_adjusted = numbers[0:len(test_pred)]
    y_true_test_vt_for_adj = y_true_test_vt

  if numbers.size > 0:
    print(f"\nTrial {k}: ")
    for metric in ["RMSE", "MAE", "MAPE", "R2-SCORE"]:
      test_metric_vt = adjusted_metrics_compute(metric, "Vanilla Transformer", y_hat_test_vt_adjusted, y_true_test_vt_for_adj)
      if metric == "RMSE":
        test_rmse_vt_adjusted = test_metric_vt
      elif metric == "MAE":
        test_mae_vt_adjusted = test_metric_vt
      elif metric == "MAPE":
        test_mape_vt_adjusted = test_metric_vt
      else:
        test_r2_score_vt_adjusted = test_metric_vt
  else:
    print(f"\nTrial {k}: no values in output")

  if test_r2_score_vt_adjusted > test_r2_score_vt + improvement_delta:
    break

print("Elapsed LLM Time: ", timeit.default_timer() - start_time)

config.json:   0%|          | 0.00/877 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

OutOfMemoryError: CUDA out of memory. Tried to allocate 99.70 GiB. GPU 0 has a total capacity of 14.56 GiB of which 6.69 GiB is free. Including non-PyTorch memory, this process has 7.87 GiB memory in use. Of the allocated memory 7.03 GiB is allocated by PyTorch, and 431.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

## **Adjusted Test Set Predictions Performance Evaluation**

In [ ]:
plot_curves("Test-set - ", llm_model_name[0:7].replace('/','_'), "test", y_hat_test_vt_adjusted, y_true_test_vt_for_adj, test_rmse_vt_adjusted, test_mae_vt_adjusted, test_mape_vt_adjusted, test_r2_score_vt_adjusted)